<?php
/*
 * Created by selva 24/11/2010
 * email : selvakumar@contus.in
 * To mention the subscribe page form.
 *
 * Updated by : sathish 24/01/2011
 * Default Newsletter subscribe page.
 * */

$select = "";
$cities = array();
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product', 'dealcity');
$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $attributeId);
// to get the multiple cities in pages(drop down)
foreach ($attribute->getSource()->getAllOptions(true, true) as $option) {
    $value = $option['value'];
    if ($value != '') {
        $cities[$value] = $option['label'];
        $select .= "<option value='" . $option['value'] . "'>" . $option['label'] . "</option>";
    }
}
?>
<div class="main-subscribe">
<div class="subscribe-container">
    <div class="page_content clearfix">
            <h1><?php echo $this->__('Subscribe for newsletter'); ?></h1>        
        <div id="sub-content">
        <!--- subscribtion form start --->
        <a class="continue" href="<?php echo $this->getUrl() . '?task=confirmSubscribe'; ?>" id="step_one"><?php echo $this->__("If you are already a subscriber, click here to continue."); ?></a>
        <form  action="<?php echo $this->getUrl('newsletter/subscriber/new') ?>" method="post" id="newsletter-validate-detail">
                <label>City<em>*</em></label>
                    <select id="city" class="input-text required-entry" name="city">
                        <option value=""><?php echo $this->__('Select your City'); ?></option>
                        <?php echo $select; ?>
                    </select>
                <div class="clear"></div>
            <label>Email<em>*</em></label>
                    <input name="email" type="text" size="30" id="newsletter1" class="searchinput1 validate-email required-entry" value="<?php echo $this->__('Enter your email address here...'); ?>" onfocus="if (this.value == '<?php echo $this->__('Enter your email address here...'); ?>') {this.value = '';}" onblur="if (this.value == '') {this.value = '<?php echo $this->__('Enter your email address here...'); ?>';}"  />
<!--                <div id="error_msg" style="color:red; font-family: Helvetica, sans-serif; font-size: 10px; position: absolute;"></div>-->
            <div class="button_container">
                    <input type="hidden" name="task" id="task" value="confirmSubscribe" />
                    <button type="submit" title="<?php echo $this->__('Continue') ?>" class="button"><span><?php echo $this->__('Subscribe') ?></span></button>
            </div>
        </form>
        <!--- subscribtion form end --->
        </div>
    </div>

</div>
    </div>
<div id="logo_container">
<h1 class="logo" >
        <a href="<?php echo $this->getUrl(); ?>"><img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" width="250" height="31" alt="logo" title="Logo" /></a>
    </h1>
</div>
<script type="text/javascript">
    //<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
</script>
