<?php
$upcomingEnabled=Mage::getStoreConfig('deal/upcoming/as_upcoming');
$products = array();
//$products = $this->getFeaturedProduct(0,5);
$currentTime = Mage_Core_Model_Locale::date(null, null, "en_US", true);
$i = 0;
$products = $this->getUpcomingProduct();
?>
<?php
$resource = Mage::getSingleton('core/resource');
$read = $resource->getConnection('catalog_read');
$orderTable = $resource->getTableName('sales/order');
$city = Mage::getSingleton('core/session')->getCity();
//print_r($city);exit;
$salesflatorderitem = (string) Mage::getConfig()->getTablePrefix() . 'sales_flat_order_item';
$total_orders = "0";
$id = "0";
$a = 0;
foreach ($products as $_product) {
    $cities =explode(',',$_product->getcity());
        if (in_array($city, $cities)) {
        $a++;
    }
}
$var = $a;
$attributeId = Mage::getResourceModel('eav/entity_attribute')->getIdByCode('catalog_product', 'dealcity');
$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', '$attributeId');
foreach ($attribute->getSource()->getAllOptions(true, true) as $option) {
     if ($option['value'] != '') {
    $value = $option['value'];
    $cities[$value] = $option['label'];
     }
}

if (count($products) > 0 && $upcomingEnabled == 1) {
    foreach ($products as $_product) {
       $cities =explode(',',$_product->getdealcity());
        if (in_array($city, $cities)) {

            //code to check if the deal is current or not, if deal is current, deal will not be displayed, elseif the deal time is over then deal will be displayed
            $startTime = $_product->getstarttime();
            $ProductToDate = $_product->getResource()->formatDate($_product->getspecial_to_date(), false);
            $ProductFromDate = $_product->getResource()->formatDate($_product->getspecial_from_date(), false);
            $Fromtime = strtotime($ProductFromDate. ' ' . $startTime);
            if (strtotime(date("Y-m-d", $Fromtime)) > strtotime($currentTime)) {
?>
<?php
                if (!$_product->isGrouped()) {
?>
<?php
                    $current_product = $_product->getProductUrl();
                    $productId= $_product->getId();
                    $todayDate = $_product->getResource()->formatDate($_product->getspecial_from_date(), false);
                    $fromdate = date('F jS, Y', strtotime($todayDate)); //
                    //$this->formatDate($_order->getCreatedAtStoreDate(), 'long'))

                    $discount_price = $_product->getPrice() - $_product->getSpecialPrice();
                    $discount = ($discount_price * 100) / $_product->getPrice();
                    $discount = round($discount);

                    // getting value of base URL to prepare URL, for recent deals view page
                    //starts
                    $baseUrl = Mage::getBaseUrl();
                    $URL = $current_product;
                    //ends

                    $dealStatus[0] = "complete";
                    $dealStatus[1] = "processing";
                    $select = $read->select()
                                    ->from(array('cp' => $orderTable))
                                    ->join(array('pei' => $salesflatorderitem), 'pei.order_id=cp.entity_id', array())
                                    ->where('pei.product_id=?', $productId)
                                    ->where('cp.status IN (?)', $dealStatus);

                    $orders_list = $read->fetchAll($select);

                    $fetch_list = array();
                    $quantity = array();
                    $quantity[0] = "0";

                    //echo $select;
                    if (count($orders_list) > 0) {

                        foreach ($orders_list as $rows) {

                            $order_id = $rows['entity_id'];
                            $order = Mage::getModel('sales/order')->load($order_id);

                            $items = $order->getAllItems();
                            //print_r($items);
                            $itemcount = count($items);
                            $name = array();
                            $unitPrice = array();
                            $sku = array();
                            $ids = array();
                            $qty = array();
                            foreach ($items as $itemId => $item) {
                                if ($productId == $item->getProductId()) {
                                    $total_orders = $total_orders + 1;
                                    $qty[0] = $item->getQtyOrdered();
                                    $quantity[0] = $quantity[0] + $qty[0];
                                }
                            }
                        }
                    }
?>
                    <div class="clsbord">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" width="192" height="130" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"/>
                        <span class="offer-bg"><?php echo $discount . "%"; ?> <?php echo $this->__('Off') ?></span>
                        <h6 class="head-title"><?php echo substr($this->htmlEscape($_product->getName()), 0, 25) . "..." ?></h6>
                        <p class="fineprint"><?php echo substr($this->htmlEscape($_product->getFineprint()), 0, 100) ?></p>
                    </div>
<?php
                }
                $i = $i + 1;
            }
        }
    }
} if($i==0) {
    echo "<h1 class='no-active-deal'>No Upcoming Deals!</h1>";
}
?>
