<?php 
if(Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/active")){

	// echo "<pre>";
	// print_r($this->getRequest());
	// echo "</pre>";
	if(Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/processing_image")){
		$processing_image_path = Mage::getBaseUrl()."media/developersindia.info/ajaxaddtocart/images/".Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/processing_image");
	}else{
		$processing_image_path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."/adminhtml/default/default/images/ajax-loader-tr.gif";
	}
	
	// button bg colors, border colors and font colors
	$button_bg_color = (Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/button_bg_color"))?(Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/button_bg_color")):"#F18200";
	
	$button_border_color = (Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/button_border_color"))?(Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/button_border_color")):"#DE5400";
	
	$button_font_color = (Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/button_font_color"))?(Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/button_font_color")):"#FFFFFF";	
?>

<?php $request_uri = $this->getRequest()->getRequestUri(); ?>
<?php $checkout_url = Mage::helper('checkout/cart')->getCartUrl(); ?>
<?php $update_tolink_url = Mage::helper('checkout/cart')->getCartUrl()."getUpdatedTopCartLink/"; ?>
<?php $home_url = Mage::getBaseUrl(); ?>
<?php 
	$ok_button_label = Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/go_to_cart_text");
	$cancel_button_label = Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/continue_shopping_text");
	$delete_confirm_text = (Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/delete_confirm_text"))?(Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/delete_confirm_text")):"Are you sure?";
	$enable_success_message = Mage::getStoreConfig("ajaxaddtocart/ajaxaddtocart_settings/enable_success_message");
?>

<div style="display: none;color:#D85909;font-size:1.1em;font-weight:bold;opacity:0.8;position:fixed; _position:absolute; text-align:center;z-index:500; top:50%; left:50%;" id="loading-mask">
	<p id="loading_mask_loader" class="loader" style="border:2px solid #CCCCCC; color:#D85909; font-weight:bold; left:50%; margin-left:-120px; padding:15px 60px; position:fixed; text-align:center; top:45%; width:120px; z-index:1000; background:#FFFFFF none repeat scroll 0 0;">
		<img alt="Loading..." src="<?php echo $processing_image_path; ?>" />
	</p>
</div>

<div style="display: none;color:#D85909;font-size:1.1em;position:fixed; _position:absolute; text-align:center;z-index:500; top:50%; left:30%;" id="after-loading-success-message">
	<p id="success-message-container" class="loader" style="border:2px solid #CCCCCC; color:#D85909;left:35%; /*margin-left:-120px;*/ padding:15px 30px; position:fixed; text-align:center; top:45%; width:300px; z-index:1000; background:#FFFFFF none repeat scroll 0 0;">	
	</p>
</div>

<div style="display: none;color:#D85909;font-size:1.1em;position:fixed; _position:absolute; text-align:left;z-index:500; background-color:#fff; top:0%; left:30%; padding:10px;" id="product_type_data_container"></div>
<div id="product_type_data_temp_container" style="display:none;"></div>

<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS)."developersindia.info/ajax-addtocart.js";?>"></script>

<script type='text/javascript'>
	setAllTheUrls('<?php echo $request_uri; ?>', '<?php echo $checkout_url; ?>', '<?php echo $update_tolink_url; ?>', '<?php echo $home_url; ?>', '<?php echo $ok_button_label; ?>', '<?php echo $cancel_button_label;?>', '<?php echo $delete_confirm_text;?>', '<?php echo $enable_success_message;?>', '<?php echo $button_bg_color;?>', '<?php echo $button_border_color;?>', '<?php echo $button_font_color;?>');
	
	Event.observe(window, 'load', function() {
	  findAndCleanUpDeleteUrls();
	});

</script>
<?php
}
?>